In [1]:
import pandas as pd
import numpy as np
import math

In [3]:
sal = pd.read_csv("city_employee_salaries.csv")

In [4]:
sal

,Id,EmployeeName,JobTitle,Department,Gender,Age,EducationLevel,YearsOfService,HireYear,Status,...,PerformanceRating,SickDaysUsed,CommuteMiles,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,1,Robert Hernandez,Clerk,Administrative Services,Male,51.0,Bachelor,19,2003,FT,...,3,6,18.8,57322.04,0.00,0.00,18907.67,57322.04,76229.71,2022
1,2,Jose Taylor,Firefighter,Fire,F,49.0,High School,8,2017,PT,...,3,8,17.7,85115.78,2836.78,0.00,7184.38,87952.56,95136.94,2025
2,3,David Moore,IT Operations Support Admin,Technology,Male,NaN,Associate,3,2019,FT,...,3,8,4.7,117698.62,0.00,0.00,38105.18,117698.62,155803.80,2022
3,4,Luis Hall,Accountant,Controller,Male,37.0,Doctorate,5,2018,FT,...,2,1,2.9,161489.93,0.00,0.00,52402.66,161489.93,213892.59,2023
4,5,Nicole Tran,Librarian,Library,Female,37.0,High School,1,2021,FT,...,3,8,2.6,96182.50,0.00,0.00,31488.01,96182.50,127670.51,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1203,1204,Sofia Taylor,Parking Control Officer,Transportation,Female,36.0,Associate,6,2017,FT,...,5,6,7.8,66756.36,17446.35,0.00,22568.42,84202.71,106771.13,2023
1204,1205,Kevin Miller,Custodian,Public Works,Male,28.0,High School,0,2024,FT,...,4,5,4.3,71909.32,26722.92,345.06,23910.81,98977.30,122888.11,2024
1205,1206,James Miller,Electrician,Public Works,Male,19.0,Bachelor,0,2024,FT,...,3,8,8.5,118976.09,0.00,14953.30,35559.43,133929.39,169488.82,2024
1206,1207,Luis Young,Firefighter,Fire,Male,55.0,High School,11,2012,FT,...,3,18,7.5,143792.24,96332.15,0.00,43404.80,240124.39,283529.19,2023
1207,1208,Kevin Tran,Police Officer,Police,Male,32.0,Bachelor,3,2019,PT,...,4,8,31.2,60084.01,24969.09,1157.74,5312.68,86210.84,91523.52,2022

In [6]:
sal.sort_values(by="Status") # sorting

,Id,EmployeeName,JobTitle,Department,Gender,Age,EducationLevel,YearsOfService,HireYear,Status,...,PerformanceRating,SickDaysUsed,CommuteMiles,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,1,Robert Hernandez,Clerk,Administrative Services,Male,51.0,Bachelor,19,2003,FT,...,3,6,18.8,57322.04,0.00,0.00,18907.67,57322.04,76229.71,2022
2,3,David Moore,IT Operations Support Admin,Technology,Male,NaN,Associate,3,2019,FT,...,3,8,4.7,117698.62,0.00,0.00,38105.18,117698.62,155803.80,2022
3,4,Luis Hall,Accountant,Controller,Male,37.0,Doctorate,5,2018,FT,...,2,1,2.9,161489.93,0.00,0.00,52402.66,161489.93,213892.59,2023
4,5,Nicole Tran,Librarian,Library,Female,37.0,High School,1,2021,FT,...,3,8,2.6,96182.50,0.00,0.00,31488.01,96182.50,127670.51,2022
5,6,Emily Wilson,Transit Operator,Transportation,Female,38.0,Bachelor,0,2024,FT,...,4,3,14.1,87132.61,3833.80,686.16,24710.48,91652.57,116363.05,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183,1184,Mary Rodriguez,Sergeant,Police,Female,20.0,High School,2,2022,PT,...,2,7,7.0,72924.63,0.00,0.00,9895.83,72924.63,82820.46,2024
1188,1189,Grace Lopez,Police Officer,Police,Female,29.0,Bachelor,4,2019,PT,...,3,11,12.3,45328.21,8615.35,0.00,2383.37,53943.56,56326.93,2023
1192,1193,Tuan Lee,Firefighter,Fire,Male,54.0,Bachelor,16,2009,PT,...,3,8,16.3,72460.61,28906.08,7828.98,4879.92,109195.67,114075.59,2025
1198,1199,Laura Kim,Registered Nurse,Public Health,Female,37.0,Bachelor,10,2015,PT,...,3,4,13.3,92606.47,43771.22,0.00,8519.09,136377.69,144896.78,2025
1207,1208,Kevin Tran,Police Officer,Police,Male,32.0,Bachelor,3,2019,PT,...,4,8,31.2,60084.01,24969.09,1157.74,5312.68,86210.84,91523.52,2022

In [12]:
sal[sal["HireYear"] == 2025]

,Id,EmployeeName,JobTitle,Department,Gender,Age,EducationLevel,YearsOfService,HireYear,Status,...,PerformanceRating,SickDaysUsed,CommuteMiles,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
108,109,Brian Lewis,Police Officer,Police,Male,25.0,Master,0,2025,FT,...,5,12,1.9,110423.62,31596.45,0.00,34737.82,142020.07,176757.89,2025
147,148,John Hall,Registered Nurse,Public Health,Male,26.0,Bachelor,0,2025,FT,...,3,2,11.3,153900.94,29366.13,11011.63,48306.84,194278.70,242585.54,2025
179,180,Marcus Jones,Gardener,Recreation & Parks,Male,34.0,Master,0,2025,FT,...,4,6,12.8,70831.21,0.00,0.00,24161.42,70831.21,94992.63,2025
201,202,Michael Clark,Custodian,Public Works,Nonbinary,30.0,Master,0,2025,FT,...,3,5,15.1,64170.68,23904.45,0.00,19379.50,88075.13,107454.63,2025
241,242,Emily Hernandez,Custodian,Public Works,Female,19.0,Bachelor,0,2025,FT,...,4,6,10.8,59718.53,6887.40,4096.59,19503.51,70702.52,90206.03,2025
251,252,Carlos Martin,CUSTODIAN,Public Works,Male,25.0,Bachelor,0,2025,FT,...,3,10,4.1,56932.87,17749.77,0.00,20126.43,74682.64,94809.07,2025
304,305,Tuan Brown,Deputy Sheriff,Sheriff,Male,20.0,Associate,0,2025,PT,...,3,9,18.5,64982.69,15533.67,0.00,8002.39,80516.36,88518.75,2025
306,307,Lisa Wong,Department Head,Administrative Services,Female,28.0,Doctorate,0,2025,PT,...,2,7,8.3,151091.74,0.00,0.00,10013.21,151091.74,161104.95,2025
316,317,Luis Lewis,Police Officer,Police,Male,39.0,Associate,0,2025,FT,...,4,11,7.4,133318.31,22699.49,0.00,37990.55,156017.80,194008.35,2025
348,349,Nicole Moore,Police Officer,Police,Female,35.0,Master,0,2025,FT,...,4,11,24.4,130960.56,1790.09,0.00,43121.65,132750.65,175872.30,2025
354,355,Emily Martin,Registered Nurse,Public Health,Female,35.0,Master,0,2025,FT,...,5,5,14.9,135990.37,0.00,0.00,47083.99,135990.37,183074.36,2025
415,416,Sofia Williams,Electrician,Public Works,Female,38.0,High School,0,2025,FT,...,4,7,10.2,130521.46,5640.29,0.00,39203.23,136161.75,175364.98,2025
550,551,Kevin Lopez,CLERK,Administrative Services,Male,24.0,Master,0,2025,FT,...,4,2,4.9,51445.42,0.00,8631.59,16760.41,60077.01,76837.42,2025
603,604,Hannah Young,Clerk,Administrative Services,Female,35.0,High School,0,2025,FT,...,3,9,11.3,40881.45,19571.57,0.00,13167.30,60453.02,73620.32,2025
605,606,Nicole Johnson,Librarian,Library,Female,27.0,Bachelor,0,2025,PT,...,4,6,8.0,53863.74,0.00,0.00,3757.34,53863.74,57621.08,2025
626,627,Andre Wong,Transit Operator,Transportation,Nonbinary,27.0,Associate,0,2025,FT,...,3,8,9.0,80660.69,42914.00,5416.07,24680.60,128990.76,153671.36,2025
648,649,Jose Kim,Sergeant,Police,Male,32.0,Master,0,2025,FT,...,5,6,33.1,144441.60,0.00,11946.26,44223.05,156387.86,200610.91,2025
713,714,Sofia Garcia,Custodian,Public Works,Female,23.0,Bachelor,0,2025,FT,...,3,9,2.2,60758.22,24554.39,0.00,21455.72,85312.61,106768.33,2025
731,732,Maria Rodriguez,Nursing Assistant,Public Health,Female,25.0,High School,0,2025,FT,...,4,7,3.0,66423.08,21426.35,0.00,23434.92,87849.43,111284.35,2025
779,780,Eric Allen,Firefighter,Fire,Male,19.0,Master,0,2025,FT,...,3,9,7.5,123783.55,9548.02,0.00,42309.52,133331.57,175641.09,2025
812,813,Jose Wilson,Registered Nurse,Public Health,Male,30.0,Bachelor,0,2025,FT,...,3,4,4.0,143545.19,13866.09,4628.91,43915.02,162040.19,205955.21,2025
871,872,Tuan Rodriguez,Recreation Leader,Recreation & Parks,Male,37.0,Bachelor,0,2025,PT,...,4,2,8.5,25785.68,0.00,0.00,2983.81,25785.68,28769.49,2025
884,885,Laura Smith,Electrician,Public Works,Female,31.0,High School,0,2025,FT,...,4,7,5.9,103425.75,0.00,0.00,30481.53,103425.75,133907.28,2025
935,936,Brian Clark,Parking Control Officer,Transportation,Male,43.0,Associate,0,2025,FT,...,5,7,24.1,65534.94,606.52,0.00,23215.07,66141.46,89356.53,2025
1043,1044,Michael Williams,Transit Operator,Transportation,Male,31.0,Bachelor,0,2025,FT,...,4,15,15.4,86915.91,0.00,6152.27,25843.31,93068.18,118911.49,2025
1060,1061,Andre Davis,Police Officer,Police,Male,44.0,Associate,0,2025,FT,...,5,9,5.9,112524.40,26572.80,3855.61,40181.63,142952.81,183134.44,2025
1152,1153,Carlos Moore,Accountant,Controller,Male,NaN,Bachelor,0,2025,PT,...,3,2,6.8,40660.92,0.00,0.00,4676.25,40660.92,45337.17,2025
1177,1178,Eric Taylor,Accountant,Controller,Male,26.0,Bachelor,0,2025,PT,...,2,4,2.5,67321.88,0.00,0.00,7568.35,67321.88,74890.23,2025