In [1]:
!pip install lxml
!pip install html5lib
!pip install BeautifulSoup4

Collecting lxml
  Downloading lxml-6.1.3-cp314-cp314-win_amd64.whl.metadata (3.4 kB)
Downloading lxml-6.1.3-cp314-cp314-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ---------------------------------------- 4.1/4.1 MB 22.7 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.3
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in C:\Users\Rotte\anaconda3\Lib\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in C:\Users\Rotte\anaconda3\Lib\site-packages (from html5lib) (0.5.1)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Installing collected packages: html5lib
Successfully installed html5lib-1.1
Requirement already satisfied: BeautifulSoup4 in C:\Users\Rotte\anaconda3\Lib\site-packages (4.15.0)
Requirement already satisfied: soupsieve>=1.6.1 in C:\Users\Rotte\anaconda3\Lib\site-packages (from BeautifulSoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in C:\Users\Rotte\anaconda3\Lib\site-packages (from BeautifulSoup4) (4.16.0)

In [8]:
sal_df = pd.read_csv("Salaries_data.csv")

In [9]:
sal_df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [7]:
import pandas as pd
import numpy as np
import math

In [10]:
failed_bank = pd.read_html("https://www.fdic.gov/bank-failures/failed-bank-list")

In [13]:
failed_bank[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
5,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
6,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
7,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
8,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
9,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
10,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
11,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
12,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
13,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
14,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
15,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
16,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
17,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
18,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
19,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
20,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
21,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
22,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
23,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
24,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528